### ISSUE TITLE
USB Gets disconnect randomly

### ISSUE THREAD

**Issue by HarunKilic** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#106]
Hi, i have an issue with the USB's, and also Bluetooth at the same time. 
I have connected USB-C to.my monitor, which has Mouse connected to it. And using apple bluetooth keyboard. 
After some while, the keyboard and mouse and etc gets disconnected and not useable. 
Tried to unplug and plug in, didnt work. Also tried to sleep and awake, didnt work. Only solution was to restart. 
I can see that they're connected at System Report. 

I am using Catalina 10.15.7 on my XPS 9570. 

Let me know if any further information is needed.

**Comment by Sencudra** [comment]
@Fl4zher Had the same problem with USB-hub (1-to-5). Little before the system disconnected all my USB ports i've been observing my mouse get freezing. I thought that maybe the devices connected do not have enough power supply and at some point the system knocks them **all** out. Unfortunately, I don't have any deep understanding of how all those magic works (Thank you @LuletterSoul ))0) and maybe the problem is different, but what helped me is to switch to USB-hub with an external power supply. During the last 2 months, I don't have any problems at all.

**Comment by HarunKilic** [comment]
Thanks, i will try to see if that helps. I have currently 2 hubs, one from the screen, and one external hub with its own powersupply. I'll try to switch between them and see if it makes diffirence.

**Comment by xxxzc** [comment]
@Fl4zher @Sencudra Can you help me test this solution:

1. add following to device properties：

```
                         <key>PciRoot(0x0)/Pci(0x14,0x0)</key>
			<dict>
				<key>device-id</key>
				<data>
				L6EAAA==
				</data>
			</dict>
```

2. Replace SSDT-UIAC.aml+USBInjectALL.kext or USBPorts.kext with this one 
[USBPorts.kext.zip](https://github.com/LuletterSoul/Dell-XPS15-9570-macOS/files/5564059/USBPorts.kext.zip)

**Comment by xxxzc** [comment]
Sorry it's not working

**Comment by HarunKilic** [comment]
I did not have the problem again after changing the USB. Seems like it is working like a charm now! :)

**Comment by xxxzc** [comment]
Can you give me your USB Hub's model? I bought the one with power supply but this problem still exists.

**Comment by HarunKilic** [comment]
Sure, its Dell D3100
